#!/usr/bin/env bash
# scaffold.sh - install the agent-engineering kit into a project.
#
# Deterministic by design. There is no model judgment anywhere in this file,
# which is the point: the parts of a workflow system that can be checked by an
# exit code should never be left to a prompt.
#
# Everything is create-if-absent or write-between-markers, so running it twice
# changes nothing. Run with --dry-run to see the plan without touching disk.

set -euo pipefail

AE_SELF="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib.sh
. "$AE_SELF/lib.sh"

AE_KIT_ROOT="$(cd -P "$AE_SELF/.." && pwd)"
AE_KIT_VERSION="$(cat "$AE_SELF/kit-version.txt" 2>/dev/null || echo unknown)"
AE_KIT_REPO="overthinkercurious/agent-engineering"
export AE_KIT_VERSION AE_KIT_REPO

DRY=0
ROOT=""

usage() {
  cat <<'USAGE'
Usage: scaffold.sh [--dry-run] [--root DIR]

  --dry-run   Print what would change and exit 0 without writing anything.
  --root DIR  Install into DIR instead of the detected project root.
  -h, --help  This message.

Creates .dev/, copies the kit scripts to .dev/kit/, writes ENGINEERING.md if
absent, and writes a pointer block into the instruction file of every detected
tool. Never overwrites ENGINEERING.md. Never writes outside the project root.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY=1; shift ;;
    --root)    ROOT="${2:-}"; [ -n "$ROOT" ] || ae_die "--root needs a directory"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) ae_die "unknown argument: $1 (try --help)" ;;
  esac
done

# ------------------------------------------------------ preconditions -------

if [ -n "$ROOT" ]; then
  [ -d "$ROOT" ] || ae_die "--root is not a directory: $ROOT"
  ROOT="$(cd -P "$ROOT" && pwd)"
else
  ROOT="$(ae_project_root)"
fi

TARGETS_YML="$AE_KIT_ROOT/references/targets.yml"
ASSETS="$AE_KIT_ROOT/assets"
[ -f "$TARGETS_YML" ] || ae_die "missing references/targets.yml next to the scripts (looked in $AE_KIT_ROOT)"
[ -d "$ASSETS" ]      || ae_die "missing assets/ next to the scripts (looked in $AE_KIT_ROOT)"

TSV="$(mktemp "${TMPDIR:-/tmp}/ae-targets.XXXXXX")"
BODY="$(mktemp "${TMPDIR:-/tmp}/ae-body.XXXXXX")"
trap 'rm -f "$TSV" "$BODY"' EXIT
ae_targets_tsv "$TARGETS_YML" > "$TSV"
[ -s "$TSV" ] || ae_die "targets.yml parsed to nothing - check its indentation"

SUMMARY="$(mktemp "${TMPDIR:-/tmp}/ae-sum.XXXXXX")"
trap 'rm -f "$TSV" "$BODY" "$SUMMARY"' EXIT
note() { printf '%s\t%s\n' "$1" "$2" >> "$SUMMARY"; }

printf '\nagent-engineering v%s\n' "$AE_KIT_VERSION"
printf 'project: %s\n' "$ROOT"
[ "$DRY" = "1" ] && printf '%sdry run - nothing will be written%s\n' "$AE_C_YEL" "$AE_C_OFF"

if ! (cd "$ROOT" && git rev-parse --git-dir >/dev/null 2>&1); then
  ae_warn "not a git repository - the kit's durable records (.dev/tasks, .dev/decisions) only mean something when they are committed"
fi

# ------------------------------------------------------------ .dev/ ---------

ae_head "runtime directories"
for d in tasks decisions knowledge rules context scratch evidence; do
  target="$ROOT/.dev/$d"
  ae_assert_inside "$ROOT" "$target"
  if [ -d "$target" ]; then
    ae_info ".dev/$d/ exists"; note unchanged ".dev/$d/"
  else
    [ "$DRY" = "1" ] || { mkdir -p "$target"; : > "$target/.gitkeep"; }
    ae_ok ".dev/$d/ created"; note created ".dev/$d/"
  fi
done

# ------------------------------------------------------- kit copy -----------
# The pointer block tells operators to run `bash .dev/kit/scripts/doctor.sh`,
# so the scripts have to exist at a stable path that survives a fresh clone.
# Skill directories do not: the skills CLI may have symlinked them, and a
# symlink committed from Windows clones back as a text stub.

ae_head "kit runtime copy"
KIT_DEST="$ROOT/.dev/kit"
if [ "$(cd -P "$AE_KIT_ROOT" && pwd)" = "$(cd -P "$KIT_DEST" 2>/dev/null && pwd || echo /nonexistent)" ]; then
  ae_info ".dev/kit/ is the source - skipping self-copy"
  note unchanged ".dev/kit/"
else
  changed=0
  for sub in scripts references assets; do
    [ -d "$AE_KIT_ROOT/$sub" ] || continue
    if ! diff -r -q "$AE_KIT_ROOT/$sub" "$KIT_DEST/$sub" >/dev/null 2>&1; then changed=1; fi
  done
  if [ "$changed" = "0" ]; then
    ae_info ".dev/kit/ up to date"; note unchanged ".dev/kit/"
  else
    if [ "$DRY" != "1" ]; then
      mkdir -p "$KIT_DEST"
      for sub in scripts references assets; do
        [ -d "$AE_KIT_ROOT/$sub" ] || continue
        rm -rf "${KIT_DEST:?}/$sub"
        cp -R "$AE_KIT_ROOT/$sub" "$KIT_DEST/$sub"
      done
      chmod +x "$KIT_DEST/scripts/"*.sh 2>/dev/null || true
      cat > "$KIT_DEST/README.md" <<EOF
Generated by agent-engineering v$AE_KIT_VERSION. Do not hand-edit.
This directory is replaced wholesale every time setup runs.
EOF
    fi
    ae_ok ".dev/kit/ written (scripts, references, assets)"; note written ".dev/kit/"
  fi
fi

VFILE="$ROOT/.dev/kit-version"
if [ -f "$VFILE" ] && [ "$(cat "$VFILE")" = "$AE_KIT_VERSION" ]; then
  ae_info ".dev/kit-version is $AE_KIT_VERSION"; note unchanged ".dev/kit-version"
else
  [ "$DRY" = "1" ] || printf '%s\n' "$AE_KIT_VERSION" > "$VFILE"
  ae_ok ".dev/kit-version set to $AE_KIT_VERSION"; note written ".dev/kit-version"
fi

# --------------------------------------------------- ENGINEERING.md ---------
# Human-owned. Never overwritten, at any version, for any reason.

ae_head "ENGINEERING.md"
ENG="$ROOT/ENGINEERING.md"
if [ -f "$ENG" ]; then
  ae_info "ENGINEERING.md exists - left untouched (it is human-owned)"
  note unchanged "ENGINEERING.md"
else
  [ "$DRY" = "1" ] || ae_render "$ASSETS/ENGINEERING.md.template" > "$ENG"
  ae_ok "ENGINEERING.md created from template (placeholders only - fill it in)"
  note created "ENGINEERING.md"
fi

# ------------------------------------------------ instruction pointers ------

ae_head "instruction files"
detected_any=0
for id in $(ae_target_ids "$TSV"); do
  ifile="$(ae_target_field "$TSV" "$id" instruction_file)"
  style="$(ae_target_field "$TSV" "$id" pointer_style)"
  detect="$(ae_target_field "$TSV" "$id" detect)"
  always="$(ae_target_field "$TSV" "$id" always)"
  disp="$(ae_target_field "$TSV" "$id" display)"
  conf="$(ae_target_field "$TSV" "$id" confidence)"
  [ -n "$ifile" ] || continue

  if [ "$always" != "true" ] && ! ae_target_detected "$ROOT" "$detect"; then
    ae_info "$disp not detected - skipped"
    continue
  fi
  detected_any=1

  case "$style" in
    import) ae_render "$ASSETS/claude-import.md" > "$BODY" ;;
    block)  ae_render "$ASSETS/pointer-block.md" > "$BODY" ;;
    *)      ae_die "unknown pointer_style '$style' for target '$id'" ;;
  esac

  path="$ROOT/$ifile"
  ae_assert_inside "$ROOT" "$path"
  st="$(ae_write_block "$path" "" "$BODY" "$DRY")"
  case "$st" in
    unchanged) ae_info "$ifile unchanged" ;;
    *)         ae_ok "$ifile $st ($disp)" ;;
  esac
  note "$st" "$ifile"
  [ "$conf" = "low" ] && ae_warn "$disp path confidence is low - verify it before relying on this install"
done

if [ "$detected_any" = "0" ]; then
  ae_warn "no AI tool detected in this project - only AGENTS.md was written"
fi

# ------------------------------------------------------- .gitignore ---------

ae_head ".gitignore"
ae_render "$ASSETS/gitignore.fragment" > "$BODY"
GI="$ROOT/.gitignore"
st="$(ae_write_block "$GI" "# " "$BODY" "$DRY")"
case "$st" in
  unchanged) ae_info ".gitignore unchanged" ;;
  *)         ae_ok ".gitignore $st (suite excluded, working zones excluded)" ;;
esac
note "$st" ".gitignore"

# ---------------------------------------------------------- summary ---------

ae_head "summary"
for s in created written updated unchanged; do
  n="$(awk -F'\t' -v s="$s" '$1==s' "$SUMMARY" | wc -l | tr -d ' ')"
  [ "$n" = "0" ] && continue
  printf '  %-10s %s\n' "$s" "$(awk -F'\t' -v s="$s" '$1==s { printf "%s ", $2 }' "$SUMMARY")"
done

if [ "$DRY" = "1" ]; then
  printf '\n%sdry run complete - no files were written%s\n\n' "$AE_C_YEL" "$AE_C_OFF"
else
  printf '\nNext: bash .dev/kit/scripts/doctor.sh\n\n'
fi
