// Shared rendering and snapshot rules; no repository code is executed here.
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// The generator's own version, stamped into every block it writes. Without it
// a survey cannot say it predates a fix: the stamp recorded what was read
// (snapshot, input sha, commit) and never what read it, so an artifact
// produced by an older kit looked exactly like a current one. It lives inside
// the skill because only the skill directory is copied into a project;
// test-packaging asserts it matches kit-version.txt and every manifest.
const KIT_VERSION = (() => {
  try {
    const here = dirname(fileURLToPath(import.meta.url))
    return JSON.parse(readFileSync(join(here, '..', 'references', 'kit.json'), 'utf8')).version || 'UNKNOWN'
  } catch { return 'UNKNOWN' }
})()

export const esc = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>')
export const table = (headers, rows, empty) => rows.length
  ? [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((row) => `| ${row.map(esc).join(' | ')} |`)].join('\n') + '\n'
  : `_${empty}_\n`

export function snapshot(a) {
  return a.provenance?.fingerprint ?? a.snapshot?.fingerprint ?? a.snapshot?.digest ?? createHash('sha256')
    .update(JSON.stringify({ ...a, generated_at: undefined })).digest('hex')
}

export function stamp(a, text) {
  return `<!-- agent-engineering:snapshot:${snapshot(a)} -->\n` +
    `<!-- agent-engineering:kit:${KIT_VERSION} -->\n` +
    `<!-- Generated by agent-engineering ${KIT_VERSION} from .dev/context/analysis.json\n` +
    `     input sha256 ${createHash('sha256').update(text).digest('hex')}\n` +
    `     analysed ${a.generated_at ?? 'UNKNOWN'}; commit ${a.git?.head ?? 'UNKNOWN'}; dirty ${a.git?.dirty ?? 'UNKNOWN'} -->`
}

export { KIT_VERSION }

const slots = /<!-- agent-engineering:judgment:([a-z0-9-]+):start -->([\s\S]*?)<!-- agent-engineering:judgment:\1:end -->/g
const staleStart = '<!-- agent-engineering:previous-synthesis:start -->'
const staleEnd = '<!-- agent-engineering:previous-synthesis:end -->'

export function writeManaged(file, title, body) {
  const start = '<!-- agent-engineering:start -->'
  const end = '<!-- agent-engineering:end -->'
  mkdirSync(dirname(file), { recursive: true })
  let block = `${start}\n${body.trimEnd()}\n${end}`
  if (!existsSync(file)) {
    writeFileSync(file, `# ${title}\n\n${block}\n\n## Notes\n\n<!-- Human notes survive regeneration. Revalidate them when source changes. -->\n`)
    return 'created'
  }
  const current = readFileSync(file, 'utf8')
  const s = current.indexOf(start)
  const e = current.indexOf(end)
  if ((s === -1) !== (e === -1) || (s !== -1 && e < s)) throw new Error(`${file} has a half-open managed block; repair its markers before regeneration.`)
  const oldSnapshot = current.match(/<!-- agent-engineering:snapshot:([a-f0-9]+) -->/)?.[1]
  const newSnapshot = block.match(/<!-- agent-engineering:snapshot:([a-f0-9]+) -->/)?.[1]
  const completed = new Map([...current.slice(s < 0 ? 0 : s, e < 0 ? current.length : e).matchAll(slots)]
    .filter((match) => match[2].trim() && !/TODO \(judgment\)/.test(match[2])).map((match) => [match[1], match[2]]))
  let suffix = s < 0 ? '' : current.slice(e + end.length)
  if (oldSnapshot && oldSnapshot === newSnapshot) {
    block = block.replace(slots, (whole, id) => completed.has(id)
      ? `<!-- agent-engineering:judgment:${id}:start -->${completed.get(id)}<!-- agent-engineering:judgment:${id}:end -->` : whole)
  } else if (completed.size) {
    // Keep one bounded comparison copy, never an unbounded revision history.
    const previous = [...completed.values()].join('\n').replace(/<!--/g, '&lt;!--').slice(0, 12000)
    const note = `\n\n${staleStart}\n### Previous synthesis — STALE\n\nSource inputs changed (previous snapshot: ${oldSnapshot ?? 'unrecorded'}). This text is retained only for comparison; it is not current evidence.\n\n${previous}\n${staleEnd}\n`
    const prior = new RegExp(`${staleStart}[\\s\\S]*?${staleEnd}\\n?`)
    suffix = suffix.replace(prior, '').trimEnd() + note
  }
  const next = s < 0 ? `${current.trimEnd()}\n\n${block}\n` : current.slice(0, s) + block + suffix
  if (next === current) return 'unchanged'
  writeFileSync(file, next)
  return 'updated'
}

export function commandEntries(a) {
  if (Array.isArray(a.commands?.entries)) return a.commands.entries
  const runner = (a.stack?.package_managers ?? []).find((pm) => ['npm', 'pnpm', 'yarn', 'bun'].includes(pm)) ?? 'npm'
  return Object.entries(a.commands?.scripts ?? {}).map(([name, run]) => ({
    name, command: `${runner} run ${name}`, run, cwd: '.', source: 'package.json', kind: classify(name),
  })).concat((a.commands?.make_targets ?? []).map((name) => ({ name, command: `make ${name}`, cwd: '.', source: 'Makefile', kind: classify(name) })))
}

export function classify(name) {
  return [['test', /^(test|tests|spec|jest|vitest|pytest)(:|$)/],
    ['typecheck', /^(typecheck|tsc|types|check-types)(:|$)/], ['lint', /^(lint|eslint|ruff|flake8|clippy)(:|$)/],
    ['format', /^(format|fmt|prettier)(:|$)/], ['build', /^(build|compile|bundle)(:|$)/]]
    .find(([, pattern]) => pattern.test(name))?.[0] ?? 'other'
}

export function ciEntries(a) {
  return (a.commands?.ci ?? []).flatMap((workflow) => (workflow.steps ?? workflow.run_steps ?? []).map((step) =>
    typeof step === 'string' ? { run: step, cwd: '.', source: workflow.file } : { source: workflow.file, ...step }))
}

export const invocation = (entry) => entry.command ?? entry.invoke ?? entry.run ?? ''
export const commandTable = (entries) => table(['Kind', 'Command', 'Working directory', 'Source'],
  entries.map((entry) => [entry.kind ?? 'unclassified', invocation(entry), entry.cwd ?? 'UNKNOWN', entry.source ?? 'UNKNOWN']),
  'No commands detected by supported parsers; inspect component manifests and CI before concluding that no gate exists.')
